# Generated by Django 4.2.9 on 2024-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
