# Generated by Django 4.2.9 on 2024-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settings_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title3',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
    ]
