# Generated by Django 4.2.9 on 2024-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_settings_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='number',
            field=models.CharField(default=1, max_length=155, verbose_name='Процент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title6',
            field=models.CharField(default=1, max_length=155, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
