# Generated by Django 4.2.9 on 2024-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_settings_descriptions2'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='painting',
            field=models.ImageField(default=1, upload_to='portrait/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
