# Generated by Django 4.2.9 on 2024-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_settings_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hobbi',
            field=models.CharField(default=1, max_length=155, verbose_name='Хоби'),
            preserve_default=False,
        ),
    ]
