# Generated by Django 4.2.9 on 2024-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_settings_hobbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about',
            field=models.CharField(default=1, max_length=155, verbose_name='Описания обо мне'),
            preserve_default=False,
        ),
    ]
