# Generated by Django 4.2.9 on 2024-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_settings_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descriptions3',
            field=models.TextField(default=1, max_length=400, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title7',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
