# Generated by Django 4.2.9 on 2024-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_settings_descriptions3_settings_title7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwerty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title7', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('descriptions3', models.TextField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.RemoveField(
            model_name='settings',
            name='descriptions3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='title7',
        ),
    ]
