# Generated by Django 4.2.9 on 2024-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_qwerty_remove_settings_descriptions3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qwerty',
            old_name='descriptions3',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='qwerty',
            old_name='title7',
            new_name='title',
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
