# Generated by Django 4.2.9 on 2024-02-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_descriptions3_qwerty_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty',
            name='descriptions2',
            field=models.TextField(default=1, max_length=400, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title3',
            field=models.CharField(default=1, max_length=155, verbose_name='Название2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title4',
            field=models.CharField(default=1, max_length=155, verbose_name='Название3'),
            preserve_default=False,
        ),
    ]
