# Generated by Django 4.2.9 on 2024-02-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_qwerty_descriptions2_qwerty_title3_qwerty_title4'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty',
            name='title5',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title6',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка3'),
            preserve_default=False,
        ),
    ]
