# Generated by Django 4.2.9 on 2024-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_qwerty_title5_qwerty_title6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwerty',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='qwerty',
            name='title6',
        ),
        migrations.AddField(
            model_name='settings',
            name='title7',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title8',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка3'),
            preserve_default=False,
        ),
    ]
