# Generated by Django 4.2.9 on 2024-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_qwerty_title5_remove_qwerty_title6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='title7',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='title8',
        ),
        migrations.AddField(
            model_name='qwerty',
            name='number',
            field=models.CharField(default=1, max_length=155, verbose_name='ПРоцент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title5',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
    ]
