# Generated by Django 4.2.9 on 2024-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_settings_title7_remove_settings_title8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty',
            name='title6',
            field=models.CharField(default=1, max_length=155, verbose_name='НАзвание'),
            preserve_default=False,
        ),
    ]
