# Generated by Django 4.2.9 on 2024-02-20 15:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
