# Generated by Django 4.2.9 on 2024-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image1',
            field=models.ImageField(default=1, upload_to='portrait/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(default=1, upload_to='portrait/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(default=1, upload_to='portrait/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(default=1, upload_to='portrait/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
