# Generated by Django 4.2.9 on 2024-02-26 12:59

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_settings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='english',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='languages',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='russian',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок3'),
            preserve_default=False,
        ),
    ]
