# Generated by Django 4.2.9 on 2024-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_settings_english_settings_image2_settings_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty',
            name='description',
            field=models.TextField(default=1, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='description2',
            field=models.TextField(default=1, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title6',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title7',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title8',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
    ]
