# Generated by Django 4.2.9 on 2024-02-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_qwerty_description_qwerty_description2_qwerty_title6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qwerty',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='qwerty',
            name='title6',
        ),
        migrations.RemoveField(
            model_name='qwerty',
            name='title7',
        ),
        migrations.RemoveField(
            model_name='qwerty',
            name='title8',
        ),
    ]
