# Generated by Django 4.2.9 on 2024-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_qwerty_description2_remove_qwerty_title6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty',
            name='title6',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title7',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qwerty',
            name='title8',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
    ]
