# Generated by Django 4.2.9 on 2024-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='title3',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок3'),
            preserve_default=False,
        ),
    ]
